### PR TITLE
Possible wrong version in requirements.txt

### PR DESCRIPTION
**Pull request by dsblank**
Did you mean 1.16.5 rather than 1.18.5?

### CODE REVIEW

**Comment by philipperemy** [comment]
@dsblank numpy 1.18.5 was released 2 days ago: https://github.com/numpy/numpy/releases.
So that was just a requirements.txt update but it will work for sure with 1.16.5!

**Comment by dsblank** [comment]
Please put the lowest version number that will work :) The higher requirements make it so that those that can't go higher will fail.

**Comment by dsblank** [comment]
Also, can you also list the minimum Python version in setup.py, like:

https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires

We are discovering that keract doesn't work with Python2 (yes, people are still using it).

**Comment by philipperemy** [comment]
@dsblank Great insight thank you very much. I'm going to merge your PR now and will add `python_requires='>=3',`.

**Pull request merged**
