### PR TITLE
Removed keras and tensorflow requirement and updated to tf.keras

### PR DESCRIPTION
**Pull request by kzimmer-bah**
Requiring tensorflow as a dependency force installs the CPU only version of the package when users have tensorflow-gpu or nightly builds installed. Per https://github.com/tensorflow/tensorflow/issues/7166 we should avoid explicit tensorflow dependencies. Keras is also included with tensorflow now and need not be installed explicitly.

### CODE REVIEW

**Comment by philipperemy** [comment]
@kzimmer-bah thanks a lot for your PR. If you can just fix the indentation and remove the tensorflow import, CI will go green :)


```
./keract/__init__.py:2:4: E111 indentation is not a multiple of four
./keract/__init__.py:2:4: F401 'tensorflow' imported but unused
./keract/__init__.py:4:4: E111 indentation is not a multiple of four
2     E111 indentation is not a multiple of four
1     F401 'tensorflow' imported but unused
```

**Comment by philipperemy** [comment]
To change the unused import to an import check you can do: https://stackoverflow.com/questions/14050281/how-to-check-if-a-python-module-exists-without-importing-it

**Comment by kzimmer-bah** [comment]
Done. Is it best practice to use importlib to do an import check? I nearly went that route originally but it seemed more pythonic and explicit to do a try/except around the import.

**Comment by kzimmer-bah** [comment]
We're all good now. I missed running the examples before and didn't catch the layer name issue in the `get_activations` test. Since no training ops were run, the dummy model defaults to an identity op I guess. 

I also added in a GPU check to the examples and enabled memory growth. For some reason tensorflow still (been an issue since I started messing with it in 2017) allocates as much memory as possible when loading data sets and models onto the GPU. I basically have that snippet as boilerplate in most of my model scripts.

**Comment by philipperemy** [comment]
@kzimmer-bah flake8 was complaining about and I think it follows PEP8 by default so in this case I guess it was better to use the importlib module.
Anyway awesome thank you so much. Looks perfect to me!

**Comment by philipperemy** [comment]
Released in `3.1.0`

**Comment by kzimmer-bah** [comment]
Glad I could help!

**Pull request merged**
