### PR TITLE
Fixed display_heatmap

### PR DESCRIPTION
**Pull request by qwertpi**
Sorry to bombard you with PRs
After updating my installed version of keract and testing it following my previous pull request I noticed that #29 changed plt.imshow(image / 255.0) to axes.flat[i].imshow(img / 255.0) presumably due to confusion over the fact that img is the activations whereas image is the inputed image so I've renamed image to input_image to avoid future confusion.

### CODE REVIEW

**Comment by qwertpi** [comment]
I've tested both display_heatmaps and display_activations this time and tested using the code in the PR this time

**Comment by philipperemy** [comment]
image

What's changing here? :)

**Comment by philipperemy** [comment]
@qwertpi cf. above

**Comment by qwertpi** [comment]
I could have sworn I'd committed the changes but somehow appear to had only modified /usr/.../dist-packages/keract/

**Comment by philipperemy** [comment]
@qwertpi ok going to merge that!

**Comment by philipperemy** [comment]
keract-2.5.4 deployed!

**Pull request merged**
