### PR TITLE
Remove dependecy on scikit-learn and add option to produce a single heatmap per layer

### LINKED ISSUE #137: Heatmaps - ValueError: X has 20 features, but MinMaxScaler is expecting 1 features as input.
When i try to show the heatmap i get the following error:
```
conv2d (1, 32, 20, 32) 
Traceback (most recent call last):
  File "/.../keract_.py", line 46, in <module>
    keract.display_heatmaps(activations, digit, save=False, fix=True)
  File "/home/.../.local/lib/python3.8/site-packages/keract/keract.py", line 527, in display_heatmaps
    img = scaler.transform(img)
  File "/home/.../.local/lib/python3.8/site-packages/sklearn/preprocessing/_data.py", line 434, in transform
    X = self._validate_data(X, copy=self.copy, dtype=FLOAT_DTYPES,
  File "/home/.../.local/lib/python3.8/site-packages/sklearn/base.py", line 437, in _validate_data
    self._check_n_features(X, reset=reset)
  File "/home/.../.local/lib/python3.8/site-packages/sklearn/base.py", line 365, in _check_n_features
    raise ValueError(
ValueError: X has 20 features, but MinMaxScaler is expecting 1 features as input.
```

`display_activations()` (the commented line) works fine with the following code, but `display_heatmaps()` will fail:
```python
    pred = model.predict(digit)
    value = np.argmax(pred)
    print(value)

    activations = keract.get_activations(model, digit, layer_names=["conv2d"])

    # keract.display_activations(activations, save=False)
    keract.display_heatmaps(activations, digit, save=False, fix=True)
```

### PR DESCRIPTION
**Pull request by qwertpi**
I'm happy to split this into two seperate PRs if you prefer.

9943b6e7513b31be84ede03f72fba6853225c44e removes the dependency on scikit-learn and hence fixes #137 and #146.\
6abf1d5bdc5b65c0fa3914a3d14a12824b970621 adds the option to produce a single heatmap for each layer (produced by taking the mean of the activations of the filters that make up the layer) as opposed to the default behaviour of producing a heatmap for each filter. 43a8e954f6aadf0c49889fc107e5cf8e2806b2d0 makes the API documentation generally more consistently formatted.

### CODE REVIEW

**Comment by qwertpi** [comment]
I've added the `# noqa: C901` to line 463 so that the tox tests get to run but I don't know whether you'd actually want to ship with it included

**Comment by philipperemy** [comment]
@qwertpi thanks! Can you make sure the PR is green?

**Comment by philipperemy** [comment]
One single PR is good ;)

**Comment by qwertpi** [comment]
From the tracebacks it seems to me that the error is some tensorflow dependency versioning error coming from the `import tensorflow as tf`, so I don't think it was introduced by my changes?

**Comment by philipperemy** [comment]
Let me have a look.

**Comment by philipperemy** [comment]
It's probably fixed in master. Rebase or merge to fetch the new changes:
- https://github.com/philipperemy/keract/commit/7e0d48e97f94eabf5bc27abceb7e61f4723d02d3

**Comment by philipperemy** [comment]
It's green. Let me know if you think the PR is ready. If it is, I'll merge it!

**Comment by qwertpi** [comment]
> It's green. Let me know if you think the PR is ready. If it is, I'll merge it!

Yes I do think it's ready

**Comment by philipperemy** [comment]
Done!

**Pull request merged**
