### PR TITLE
tf eager mode

### PR DESCRIPTION
**Pull request by philipperemy**

### CODE REVIEW

**Comment by dsblank** [comment]
@philipperemy This would be very useful!

**Comment by philipperemy** [comment]
@dsblank run:
```
pip install keract-nightly
```

**Comment by dsblank** [comment]
:-1: Yes, sorry... I meant if it were complete, tested, and ready to use.

**Comment by philipperemy** [comment]
@dsblank yes there is a significant and ongoing effort to support all the features with eager. Will keep you posted :)

**Comment by philipperemy** [comment]
@dsblank seems like with the latest keract version (with pip install), you can fetch the activations with eager mode.

**Comment by philipperemy** [comment]
The gradients still need to have eager mode turned off.

**Comment by philipperemy** [comment]
I'll close this PR for now.

**Pull request closed without merging**
